"""Train PayloadCNN model for malicious payload detection."""
import sys
import argparse
import json
import random
from pathlib import Path

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, random_split
from torch.amp import GradScaler
from tqdm import tqdm

from src.torch_models.payload_cnn import PayloadCNN
from src.torch_models.datasets import PayloadDataset
from src.torch_models.utils import setup_gpu, EarlyStopping, save_model


def _load_hard_examples(file_path: str, model: str = "payload"):
    """Load hard examples generated by feedback loop."""
    if not file_path:
        return []
    path = Path(file_path)
    if not path.exists():
        print(f"Warning: hard examples file not found: {path}")
        return []

    records = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if obj.get("model") != model:
                continue
            text = str(obj.get("text", "")).strip()
            if len(text) < 3:
                continue
            label = int(obj.get("label", 0))
            records.append((text, label, True))
    return records


def load_payload_data(base_path, hard_examples_file=None):
    """Load malicious and benign payloads from dataset folders."""
    base = Path(base_path)
    payloads_dir = base / 'datasets' / 'security_payloads'
    curated_dir = base / 'datasets' / 'curated_benign'
    adversarial_dir = curated_dir / 'adversarial'
    
    records = []
    
    # Malicious payloads (label=1)
    for folder in ['injection', 'fuzzing', 'misc']:
        folder_path = payloads_dir / folder
        if not folder_path.exists():
            continue
        for f in folder_path.rglob('*'):
            try:
                if not f.is_file() or f.suffix not in ('', '.txt', '.lst', '.list'):
                    continue
                for line in f.read_text(errors='ignore').splitlines()[:1000]:
                    line = line.strip()
                    if line and len(line) > 3:
                        records.append((line, 1, False))
            except (OSError, PermissionError):
                continue
    
    mal_count = sum(1 for _, label, _ in records if label == 1)
    print(f"Loaded {mal_count} malicious payloads")
    
    # Load CURATED benign data first (priority)
    if curated_dir.exists():
        for f in curated_dir.glob('*.txt'):
            try:
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines():
                    line = line.strip()
                    if line and len(line) > 2:
                        records.append((line, 0, False))
            except: pass
        print(f"Loaded {sum(1 for _, label, _ in records if label == 0)} curated benign samples")
    
    # Load ADVERSARIAL benign data (critical for reducing false positives)
    adv_count_before = sum(1 for _, label, _ in records if label == 0)
    if adversarial_dir.exists():
        for f in adversarial_dir.glob('*.txt'):
            try:
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines():
                    line = line.strip()
                    if line and len(line) > 2:
                        records.append((line, 0, False))
            except: pass
        print(f"Loaded {sum(1 for _, label, _ in records if label == 0) - adv_count_before} adversarial benign samples")
    
    # Load 500k FP test dataset (JSONL format)
    fp_test_file = base / 'datasets' / 'fp_test_500k.jsonl'
    fp_count_before = sum(1 for _, label, _ in records if label == 0)
    if fp_test_file.exists():
        try:
            with open(fp_test_file, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        obj = json.loads(line.strip())
                        text = obj.get('text', '').strip()
                        if text and len(text) > 2:
                            records.append((text, 0, False))
                    except json.JSONDecodeError:
                        continue
            print(f"Loaded {sum(1 for _, label, _ in records if label == 0) - fp_count_before} samples from fp_test_500k.jsonl")
        except Exception as e:
            print(f"Warning: Could not load fp_test_500k.jsonl: {e}")

    # Load hard examples from feedback loop output
    hard_records = _load_hard_examples(hard_examples_file, model="payload")
    if hard_records:
        records.extend(hard_records)
        hard_mal = sum(1 for _, label, _ in hard_records if label == 1)
        hard_ben = sum(1 for _, label, _ in hard_records if label == 0)
        print(f"Loaded {len(hard_records)} payload hard examples ({hard_mal} malicious, {hard_ben} benign)")
    
    # Fallback: wordlists if not enough benign
    ben_count_now = sum(1 for _, label, _ in records if label == 0)
    if ben_count_now < mal_count // 2:
        wordlists = payloads_dir / 'wordlists'
        if wordlists.exists():
            for f in wordlists.rglob('*'):
                try:
                    if not f.is_file():
                        continue
                    for line in f.read_text(errors='ignore').splitlines()[:2000]:
                        line = line.strip()
                        if line and len(line) > 2 and len(line) < 100:
                            records.append((line, 0, False))
                except: pass
    
    ben_count = sum(1 for _, label, _ in records if label == 0)
    print(f"Loaded {ben_count} total benign samples")
    
    # Balance classes while prioritizing hard examples.
    mal_records = [r for r in records if r[1] == 1]
    ben_records = [r for r in records if r[1] == 0]

    if mal_records and ben_records:
        target = min(len(mal_records), len(ben_records))
        hard_mal = [r for r in mal_records if r[2]]
        hard_ben = [r for r in ben_records if r[2]]
        soft_mal = [r for r in mal_records if not r[2]]
        soft_ben = [r for r in ben_records if not r[2]]
        random.shuffle(soft_mal)
        random.shuffle(soft_ben)

        selected_mal = (hard_mal + soft_mal)[:target]
        selected_ben = (hard_ben + soft_ben)[:target]
        final = selected_mal + selected_ben
        random.shuffle(final)
    else:
        final = records

    texts = [text for text, _, _ in final]
    labels = [label for _, label, _ in final]
    
    print(f"Final dataset: {len(texts)} samples (balanced)")
    return texts, labels


def train():
    """Main training function."""
    parser = argparse.ArgumentParser()
    parser.add_argument('--hard-examples-file', type=str, default=None,
                        help='Optional JSONL hard examples generated by feedback loop')
    args = parser.parse_args()

    # Setup
    base_path = Path(__file__).parent.parent.parent
    device = setup_gpu()
    
    # Load data
    print("\n--- Loading Data ---")
    texts, labels = load_payload_data(base_path, hard_examples_file=args.hard_examples_file)
    
    if len(texts) < 100:
        print("ERROR: Not enough data. Check datasets/security_payloads/ folder.")
        return
    
    # Create dataset and split
    dataset = PayloadDataset(texts, labels, max_len=500)
    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])
    
    train_loader = DataLoader(train_ds, batch_size=64, shuffle=True, num_workers=0, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=64, shuffle=False, num_workers=0, pin_memory=True)
    
    print(f"Train: {len(train_ds)}, Val: {len(val_ds)}")
    
    # Model
    print("\n--- Creating Model ---")
    model = PayloadCNN().to(device)
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {param_count:,}")
    
    # Training setup - with label smoothing to reduce overconfidence
    criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([1.0]).to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=3, factor=0.5)
    scaler = GradScaler()
    early_stop = EarlyStopping(patience=5)
    
    # Label smoothing factor
    label_smoothing = 0.1
    
    # Training loop
    print("\n--- Training ---")
    best_val_acc = 0
    best_state = None
    
    for epoch in range(60):  # Increased from 50
        # Train
        model.train()
        train_loss = 0
        for batch in tqdm(train_loader, desc=f"Epoch {epoch+1}", leave=False):
            inputs = batch['input'].to(device)
            targets = batch['target'].to(device)
            
            optimizer.zero_grad()
            with torch.amp.autocast('cuda'):
                outputs = model(inputs)
                # Apply label smoothing: targets become 0.1 or 0.9 instead of 0 or 1
                smoothed_targets = targets * (1 - label_smoothing) + 0.5 * label_smoothing
                loss = criterion(outputs, smoothed_targets)
            
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            train_loss += loss.item()
        
        train_loss /= len(train_loader)
        
        # Validate
        model.eval()
        val_loss, correct, total = 0, 0, 0
        with torch.no_grad():
            for batch in val_loader:
                inputs = batch['input'].to(device)
                targets = batch['target'].to(device)
                with torch.amp.autocast('cuda'):
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                val_loss += loss.item()
                preds = (torch.sigmoid(outputs) > 0.5).float()  # Apply sigmoid for predictions
                correct += (preds == targets).sum().item()
                total += targets.size(0)
        
        val_loss /= len(val_loader)
        val_acc = correct / total
        
        scheduler.step(val_loss)
        
        print(f"Epoch {epoch+1}: train_loss={train_loss:.4f}, val_loss={val_loss:.4f}, val_acc={val_acc:.2%}")
        
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = model.state_dict().copy()
        
        if early_stop(val_loss):
            print("Early stopping triggered")
            break
    
    # Save best model
    print("\n--- Saving Model ---")
    model.load_state_dict(best_state)
    models_dir = base_path / 'models'
    models_dir.mkdir(exist_ok=True)
    
    # Save as TorchScript
    model.eval()
    example = torch.zeros(1, 500, dtype=torch.long).to(device)
    save_model(model, models_dir / 'payload_cnn', example)
    
    # Also save state dict
    torch.save(best_state, models_dir / 'payload_cnn.pth')
    
    print(f"✓ Model saved to models/payload_cnn.pt")
    print(f"✓ Best validation accuracy: {best_val_acc:.2%}")


if __name__ == "__main__":
    train()
