"""Train URL CNN model for malicious URL detection."""
import sys
import argparse
import json
from pathlib import Path
import random
import urllib.parse
from typing import Any, Dict, Optional, Tuple

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Subset
from torch.amp import GradScaler
from tqdm import tqdm

from src.torch_models.url_cnn import URLCNN
from src.torch_models.datasets import URLDataset
from src.torch_models.utils import setup_gpu, EarlyStopping, save_model
from src.training.training_utils import (
    binary_metrics,
    load_operational_threshold,
    stratified_index_split,
    write_training_manifest,
)
from src.data_guardrails import (
    assert_allowed_training_path,
    assert_allowed_training_paths,
)
from src.training.checkpoint import CheckpointManager


def _load_hard_examples(file_path: str, model: str = "url"):
    """Load URL hard examples generated by feedback loop."""
    if not file_path:
        return []
    path = Path(file_path)
    assert_allowed_training_path(path, context="url hard examples source")
    if not path.exists():
        print(f"Warning: hard examples file not found: {path}")
        return []

    records = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception:
                continue
            if obj.get("model") != model:
                continue
            text = str(obj.get("text", "")).strip()
            if not text:
                continue
            if not text.startswith(("http://", "https://")):
                text = f"http://{text}"
            label = int(obj.get("label", 0))
            records.append((text, label))
    return records


def generate_malicious_urls(n=50000):
    """Generate synthetic malicious URLs with common attack patterns."""
    urls = []
    short_domains = ['bit.ly', 'tinyurl.com', 'is.gd', 't.co', 'cutt.ly']
    
    # Phishing patterns
    legit_brands = ['paypal', 'amazon', 'google', 'microsoft', 'apple', 'facebook', 'netflix', 'bank']
    tlds = ['.tk', '.ml', '.ga', '.cf', '.gq', '.xyz', '.top', '.pw', '.cc', '.su']
    
    for _ in range(n // 5):
        brand = random.choice(legit_brands)
        tld = random.choice(tlds)
        # Typosquatting
        urls.append(f"http://{brand}{random.randint(1,99)}{tld}/login")
        # Subdomain abuse
        urls.append(f"http://{brand}.secure-login{tld}/verify")
        # Homograph-like
        urls.append(f"http://{brand.replace('a','4').replace('e','3')}.com/account")
        # Long subdomain
        urls.append(f"http://secure.{brand}.account.verify{tld}/auth")
        # IP-based
        urls.append(f"http://{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}/{brand}/login")
    
    # Malware/exploit patterns
    for _ in range(n // 5):
        urls.append(f"http://download{random.randint(1,999)}.xyz/file.exe")
        urls.append(f"http://{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}/malware.php")
        urls.append(f"http://free-software.tk/crack_{random.randint(1,100)}.zip")
        urls.append(f"http://update-flash.ml/player.exe")
        urls.append(f"http://cdn{random.randint(1,99)}.pw/script.js")
    
    # Encoded/obfuscated
    for _ in range(n // 10):
        urls.append(f"http://evil.com/%27%20OR%201=1--")
        urls.append(f"http://site.tk/page?id=<script>alert(1)</script>")
        urls.append(f"http://x.ml/r?u=http://phish.com")
        urls.append(f"http://bit.ly/{random.randint(100000,999999)}")

    return urls[:n]


def generate_benign_urls(n=50000):
    """Generate synthetic benign URLs."""
    urls = []
    
    domains = ['google.com', 'amazon.com', 'youtube.com', 'facebook.com', 'wikipedia.org',
               'twitter.com', 'instagram.com', 'linkedin.com', 'github.com', 'stackoverflow.com',
               'reddit.com', 'netflix.com', 'microsoft.com', 'apple.com', 'yahoo.com']
    
    paths = ['', '/about', '/contact', '/products', '/services', '/blog', '/news', 
             '/help', '/support', '/login', '/signup', '/search', '/home', '/faq']
    
    for _ in range(n):
        domain = random.choice(domains)
        path = random.choice(paths)
        proto = random.choice(['http://', 'https://'])
        www = random.choice(['', 'www.'])
        
        if random.random() < 0.3:
            # Add query params
            params = f"?q={random.choice(['search', 'query', 'item'])}&page={random.randint(1,10)}"
        else:
            params = ''
        
        urls.append(f"{proto}{www}{domain}{path}{params}")
    
    return urls


def generate_benign_hard_negative_urls(n=12000):
    """Generate benign URLs that resemble adversarial stress-test negatives."""
    urls = []
    short_domains = ['bit.ly', 'tinyurl.com', 'is.gd', 't.co', 'cutt.ly']
    safe_paths = [
        '/home',
        '/browse',
        '/wiki/Machine_learning',
        '/questions/tagged/javascript',
        '/torvalds/linux',
        '/iphone',
        '/watch?v=dQw4w9WgXcQ',
    ]
    benign_targets = [
        'https://www.google.com/search?q=python+tutorial',
        'https://github.com/torvalds/linux',
        'https://stackoverflow.com/questions/tagged/javascript',
        'https://www.wikipedia.org/wiki/Machine_learning',
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://www.apple.com/iphone',
        'https://news.ycombinator.com/',
    ]

    while len(urls) < n:
        ip_host = '.'.join(str(random.randint(1, 223)) for _ in range(4))
        path = random.choice(safe_paths)
        target = random.choice(benign_targets)
        short_domain = random.choice(short_domains)
        token = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=7))

        urls.append(f"https://{ip_host}{path}")
        if len(urls) >= n:
            break
        urls.append(f"http://{short_domain}/{token}?url={urllib.parse.quote(target, safe='')}")
        if len(urls) >= n:
            break
        urls.append(f"https://{ip_host}/?redirect={urllib.parse.quote(target, safe='')}")

    return urls[:n]


def generate_malicious_shortener_urls(n=8000):
    """Generate malicious shortener URLs that mirror stress-test shortener attacks."""
    urls = []
    short_domains = ['bit.ly', 'tinyurl.com', 'is.gd', 't.co', 'cutt.ly']

    while len(urls) < n:
        token = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=7))
        target_host = f"malicious-redirect-{random.randint(1000,9999)}.com"
        target_path = random.choice(['/login', '/security', '/payment', '/auth', '/docs'])
        target_query = random.choice([
            '',
            f"?token={random.randint(10**7, 10**8 - 1):x}",
            f"?redirect={random.choice(['profile', 'billing', 'verify'])}",
        ])
        target = urllib.parse.quote(f"http://{target_host}{target_path}{target_query}", safe='')
        short_domain = random.choice(short_domains)
        urls.append(f"http://{short_domain}/{token}?url={target}")
        if len(urls) >= n:
            break
        urls.append(f"http://{short_domain}/{token}?redirect={target}")
        if len(urls) >= n:
            break
        if random.random() < 0.4:
            homograph_domain = short_domain.replace('o', 'ο', 1) if 'o' in short_domain else short_domain
            urls.append(f"http://{homograph_domain}/{token}")
        else:
            urls.append(f"http://{short_domain}/{token}")

    return urls[:n]


def _normalize_url_candidate(raw: Any, default_scheme: str = "http://") -> Optional[str]:
    text = str(raw or "").strip()
    if not text:
        return None
    if text.startswith(("http://", "https://")):
        return text
    return f"{default_scheme}{text.lstrip('/')}"


def _new_source_bucket() -> Dict[str, int]:
    return {"total": 0, "malicious": 0, "benign": 0}


def _bump_source(summary: Dict[str, Dict[str, int]], source: str, label: int) -> None:
    bucket = summary.setdefault(source, _new_source_bucket())
    bucket["total"] += 1
    if int(label) == 1:
        bucket["malicious"] += 1
    else:
        bucket["benign"] += 1


def load_url_data(
    base_path,
    hard_examples_file=None,
    return_summary: bool = False,
    generated_hard_negative_count: int = 12000,
    generated_shortener_attack_count: int = 0,
    curated_adversarial_limit: int = 20000,
):
    """Load URL data - uses real data + improved synthetic."""
    urls, labels = [], []
    source_counts: Dict[str, Dict[str, int]] = {}
    skipped_counts: Dict[str, int] = {}

    url_dir = Path(base_path) / 'datasets' / 'url_analysis'
    live_benign_dir = Path(base_path) / 'datasets' / 'live_benign'
    curated_benign_dir = Path(base_path) / 'datasets' / 'curated_benign' / 'adversarial'
    assert_allowed_training_paths(
        [url_dir, live_benign_dir, curated_benign_dir],
        context="url training data source",
    )
    
    # === REAL MALICIOUS URLs ===
    
    # Load URLhaus malicious URLs
    real_mal = url_dir / 'real_malicious_urls.txt'
    if real_mal.exists():
        for line in real_mal.read_text(errors='ignore').splitlines():
            if line.strip().startswith('http'):
                urls.append(line.strip())
                labels.append(1)
                _bump_source(source_counts, "urlhaus_real_malicious", 1)
        print(f"Loaded {len(urls)} real malicious URLs (URLhaus)")
    
    # Load Kaggle malicious URLs (has both classes!)
    kaggle_file = url_dir / 'kaggle_malicious_urls.csv'
    if kaggle_file.exists():
        kaggle_mal, kaggle_ben = 0, 0
        for i, line in enumerate(kaggle_file.read_text(errors='ignore').splitlines()):
            if i == 0:  # Skip header
                continue
            parts = line.rsplit(',', 1)
            if len(parts) == 2:
                url, label = parts[0].strip(), parts[1].strip()
                if url and label in ('0', '1'):
                    normalized = _normalize_url_candidate(url)
                    if normalized is None:
                        skipped_counts["kaggle_csv"] = skipped_counts.get("kaggle_csv", 0) + 1
                        continue
                    numeric_label = int(label)
                    urls.append(normalized)
                    labels.append(numeric_label)
                    _bump_source(source_counts, "kaggle_csv", numeric_label)
                    if label == '1':
                        kaggle_mal += 1
                    else:
                        kaggle_ben += 1
        print(f"Loaded {kaggle_mal} malicious + {kaggle_ben} benign from Kaggle dataset")
    
    # Load synthetic malicious (for diversity)
    synth_mal = url_dir / 'synthetic_malicious_hard.txt'
    if synth_mal.exists():
        mal_before = sum(labels)
        for line in synth_mal.read_text(encoding='utf-8', errors='ignore').splitlines()[:20000]:
            normalized = _normalize_url_candidate(line)
            if normalized is None:
                skipped_counts["synthetic_malicious_hard"] = skipped_counts.get("synthetic_malicious_hard", 0) + 1
                continue
            urls.append(normalized)
            labels.append(1)
            _bump_source(source_counts, "synthetic_malicious_hard", 1)
        print(f"Loaded {sum(labels) - mal_before} synthetic malicious URLs")
    
    mal_count = sum(labels)
    
    # === REAL BENIGN URLs ===
    
    # Load Common Crawl URLs from live_benign (NEW - up to 50M)
    cc_urls = live_benign_dir / 'common_crawl_urls.jsonl'
    if cc_urls.exists():
        ben_before = len(urls) - mal_count
        import json
        with open(cc_urls, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f):
                if i >= 100000:  # Limit to 100K for balance
                    break
                try:
                    data = json.loads(line)
                    normalized = _normalize_url_candidate(data.get('text', ''))
                    if normalized is None:
                        skipped_counts["common_crawl_urls"] = skipped_counts.get("common_crawl_urls", 0) + 1
                        continue
                    urls.append(normalized)
                    labels.append(0)
                    _bump_source(source_counts, "common_crawl_urls", 0)
                except:
                    skipped_counts["common_crawl_urls"] = skipped_counts.get("common_crawl_urls", 0) + 1
        print(f"Loaded {len(urls) - mal_count - ben_before} Common Crawl URLs (live_benign)")
    
    # Load Tranco top domains (REAL benign)
    tranco_file = url_dir / 'top-1m.csv'
    if tranco_file.exists():
        ben_before = len(urls) - mal_count
        for i, line in enumerate(tranco_file.read_text(errors='ignore').splitlines()):
            if i >= 50000:  # Limit to 50K
                break
            parts = line.split(',')
            if len(parts) >= 2:
                domain = parts[1].strip()
                if domain:
                    normalized = _normalize_url_candidate(domain, default_scheme="https://")
                    if normalized is None:
                        skipped_counts["tranco_top_domains"] = skipped_counts.get("tranco_top_domains", 0) + 1
                        continue
                    if not normalized.endswith('/'):
                        normalized = f"{normalized}/"
                    urls.append(normalized)
                    labels.append(0)
                    _bump_source(source_counts, "tranco_top_domains", 0)
        print(f"Loaded {len(urls) - mal_count - ben_before} real benign domains (Tranco)")
    
    # Load synthetic benign (for diversity)
    synth_ben = url_dir / 'synthetic_benign_hard.txt'
    if synth_ben.exists():
        ben_before = len(urls) - mal_count
        for line in synth_ben.read_text(encoding='utf-8', errors='ignore').splitlines()[:20000]:
            normalized = _normalize_url_candidate(line)
            if normalized is None:
                skipped_counts["synthetic_benign_hard"] = skipped_counts.get("synthetic_benign_hard", 0) + 1
                continue
            urls.append(normalized)
            labels.append(0)
            _bump_source(source_counts, "synthetic_benign_hard", 0)
        print(f"Loaded {len(urls) - mal_count - ben_before} synthetic benign URLs")

    curated_adv_ben = curated_benign_dir / 'url_benign.txt'
    if curated_adv_ben.exists() and curated_adversarial_limit > 0:
        ben_before = len(urls) - mal_count
        for line in curated_adv_ben.read_text(encoding='utf-8', errors='ignore').splitlines()[:curated_adversarial_limit]:
            normalized = _normalize_url_candidate(line)
            if normalized is None:
                skipped_counts["curated_adversarial_url_benign"] = skipped_counts.get("curated_adversarial_url_benign", 0) + 1
                continue
            urls.append(normalized)
            labels.append(0)
            _bump_source(source_counts, "curated_adversarial_url_benign", 0)
        print(f"Loaded {len(urls) - mal_count - ben_before} curated adversarial benign URLs")

    if generated_hard_negative_count > 0:
        ben_before = len(urls) - mal_count
        for candidate in generate_benign_hard_negative_urls(generated_hard_negative_count):
            normalized = _normalize_url_candidate(candidate)
            if normalized is None:
                skipped_counts["generated_benign_hard_negatives"] = skipped_counts.get("generated_benign_hard_negatives", 0) + 1
                continue
            urls.append(normalized)
            labels.append(0)
            _bump_source(source_counts, "generated_benign_hard_negatives", 0)
        print(f"Loaded {len(urls) - mal_count - ben_before} generated benign hard-negative URLs")

    if generated_shortener_attack_count > 0:
        mal_before = sum(labels)
        for candidate in generate_malicious_shortener_urls(generated_shortener_attack_count):
            normalized = _normalize_url_candidate(candidate)
            if normalized is None:
                skipped_counts["generated_shortener_attack_urls"] = skipped_counts.get("generated_shortener_attack_urls", 0) + 1
                continue
            urls.append(normalized)
            labels.append(1)
            _bump_source(source_counts, "generated_shortener_attack_urls", 1)
        print(f"Loaded {sum(labels) - mal_before} generated malicious shortener URLs")
    
    # Fallback to generated if no data
    if len(urls) < 1000:
        print("Generating synthetic URLs (no real data found)...")
        mal_urls = generate_malicious_urls(50000)
        ben_urls = generate_benign_urls(50000)
        urls.extend(mal_urls)
        labels.extend([1] * len(mal_urls))
        urls.extend(ben_urls)
        labels.extend([0] * len(ben_urls))
        for _ in mal_urls:
            _bump_source(source_counts, "generated_malicious_fallback", 1)
        for _ in ben_urls:
            _bump_source(source_counts, "generated_benign_fallback", 0)

    # Feedback loop hard examples
    hard_examples = _load_hard_examples(hard_examples_file, model="url")
    if hard_examples:
        # Repeat hard examples to make sure they influence gradients even on large URL corpora.
        repeat_factor = 3
        for _ in range(repeat_factor):
            for url, label in hard_examples:
                urls.append(url)
                labels.append(label)
                _bump_source(source_counts, "hard_examples", label)
        hard_mal = sum(1 for _, label in hard_examples if label == 1)
        hard_ben = len(hard_examples) - hard_mal
        print(
            f"Loaded {len(hard_examples)} URL hard examples "
            f"({hard_mal} malicious, {hard_ben} benign), repeated x{repeat_factor}"
        )
    
    print(f"Total: {len(urls)} URLs ({sum(labels)} malicious, {len(labels)-sum(labels)} benign)")
    if not return_summary:
        return urls, labels
    summary = {
        "source_counts": source_counts,
        "skipped_counts": skipped_counts,
        "hard_examples_repeat_factor": 3 if hard_examples else 0,
        "totals": {
            "total": len(urls),
            "malicious": int(sum(labels)),
            "benign": int(len(labels) - sum(labels)),
        },
    }
    return urls, labels, summary


def train():
    """Main training function."""
    parser = argparse.ArgumentParser()
    parser.add_argument('--resume', action='store_true', help='Resume from checkpoint')
    parser.add_argument('--checkpoint-every', type=int, default=500, help='Save checkpoint every N batches')
    parser.add_argument('--hard-examples-file', type=str, default=None,
                        help='Optional JSONL hard examples generated by feedback loop')
    parser.add_argument('--epochs', type=int, default=60, help='Training epochs (default: 60)')
    parser.add_argument('--batch-size', type=int, default=128, help='Batch size (default: 128)')
    parser.add_argument('--num-workers', type=int, default=4, help='Dataloader workers (default: 4)')
    parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducible smoke runs')
    parser.add_argument('--base-path', type=str, default=None,
                        help='Optional repo root override for fixture-based smoke tests')
    args = parser.parse_args()
    
    base_path = Path(args.base_path) if args.base_path else Path(__file__).parent.parent.parent
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)
    device = setup_gpu()
    
    # Checkpoint manager
    ckpt_dir = base_path / 'checkpoints' / 'url'
    ckpt_mgr = CheckpointManager(str(ckpt_dir), 'url_cnn', args.checkpoint_every)
    
    # Load data
    print("\n--- Loading Data ---")
    urls, labels, data_summary = load_url_data(
        base_path,
        hard_examples_file=args.hard_examples_file,
        return_summary=True,
        generated_shortener_attack_count=8000,
    )
    
    # Create dataset and split
    dataset = URLDataset(urls, labels, max_len=200)
    train_idx, val_idx = stratified_index_split(labels, test_size=0.2, seed=42)
    train_ds = Subset(dataset, train_idx.tolist())
    val_ds = Subset(dataset, val_idx.tolist())
    
    persistent_workers = args.num_workers > 0
    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
        timeout=0,
        persistent_workers=persistent_workers,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        timeout=0,
        persistent_workers=persistent_workers,
    )
    
    print(f"Train: {len(train_ds)}, Val: {len(val_ds)}")
    
    # Model
    print("\n--- Creating Model ---")
    model = URLCNN().to(device)
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {param_count:,}")
    
    # Training setup
    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=3, factor=0.5)
    scaler = GradScaler()
    early_stop = EarlyStopping(patience=5)
    eval_threshold = load_operational_threshold("url", default=0.80)
    
    # Resume from checkpoint only when explicitly requested.
    start_epoch, start_batch, global_step = 0, 0, 0
    if args.resume:
        resume_info = ckpt_mgr.load(model, optimizer, scheduler, scaler, device)
        start_epoch = resume_info['epoch']
        start_batch = resume_info['batch_idx']
        global_step = resume_info['global_step']
        if start_batch >= len(train_loader):
            start_epoch += 1
            start_batch = 0
        if start_epoch >= args.epochs:
            print(
                f"Resume point epoch {start_epoch} is at or beyond requested --epochs {args.epochs}; "
                "saving current state without additional training."
            )
    
    # Training loop
    print("\n--- Training ---")
    best_metrics = None
    best_state = model.state_dict().copy()
    
    for epoch in range(start_epoch, args.epochs):
        # Train
        model.train()
        train_loss = 0
        batches_processed = 0
        
        epoch_start_batch = start_batch if epoch == start_epoch else 0
        
        pbar = tqdm(enumerate(train_loader), total=len(train_loader),
                    initial=epoch_start_batch, desc=f"Epoch {epoch+1}")
        
        for batch_idx, batch in pbar:
            if batch_idx < epoch_start_batch:
                continue
                
            inputs = batch['input'].to(device)
            targets = batch['target'].to(device)
            
            optimizer.zero_grad()
            with torch.amp.autocast('cuda'):
                outputs = model(inputs)
                loss = criterion(outputs, targets)
            
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            train_loss += loss.item()
            batches_processed += 1
            global_step += 1
            
            pbar.set_postfix({'loss': f'{loss.item():.4f}'})
            
            if ckpt_mgr.should_save(batch_idx):
                ckpt_mgr.save(epoch, batch_idx, model, optimizer, scheduler, scaler, global_step)
        
        ckpt_mgr.save(epoch, len(train_loader), model, optimizer, scheduler, scaler, global_step)
        
        train_loss /= max(batches_processed, 1)
        
        # Validate
        model.eval()
        val_loss = 0
        all_probs, all_targets = [], []
        with torch.no_grad():
            for batch in val_loader:
                inputs = batch['input'].to(device)
                targets = batch['target'].to(device)
                with torch.amp.autocast('cuda'):
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                val_loss += loss.item()
                probs = torch.sigmoid(outputs)
                all_probs.extend(probs.detach().cpu().numpy().tolist())
                all_targets.extend(targets.detach().cpu().numpy().tolist())
        
        val_loss /= len(val_loader)
        val_metrics = binary_metrics(all_probs, all_targets, eval_threshold)
        
        scheduler.step(val_loss)
        
        print(
            f"Epoch {epoch+1}: train_loss={train_loss:.4f}, val_loss={val_loss:.4f}, "
            f"val_f1={val_metrics['f1']:.4f}, val_recall={val_metrics['recall']:.4f}, val_fpr={val_metrics['fpr']:.4f}"
        )
        
        if best_metrics is None or (
            val_metrics['f1'],
            val_metrics['recall'],
            -val_metrics['fpr'],
        ) > (
            best_metrics['f1'],
            best_metrics['recall'],
            -best_metrics['fpr'],
        ):
            best_metrics = dict(val_metrics)
            best_state = model.state_dict().copy()
        
        if early_stop(val_loss):
            print("Early stopping triggered")
            break
    
    # Save best model
    print("\n--- Saving Model ---")
    model.load_state_dict(best_state)
    models_dir = base_path / 'models'
    models_dir.mkdir(exist_ok=True)
    
    model.eval()
    example = torch.zeros(1, 200, dtype=torch.long).to(device)
    save_model(model, models_dir / 'url_cnn', example)
    torch.save(best_state, models_dir / 'url_cnn.pth')
    write_training_manifest(
        models_dir / 'url_cnn_training_manifest.json',
        {
            "model": "url",
            "dataset_size": len(dataset),
            "train_size": len(train_ds),
            "val_size": len(val_ds),
            "operational_threshold": eval_threshold,
            "best_metrics": best_metrics or {},
            "label_counts": {
                "malicious": int(sum(labels)),
                "benign": int(len(labels) - sum(labels)),
            },
            "source_counts": data_summary["source_counts"],
            "skipped_counts": data_summary["skipped_counts"],
            "hard_examples_repeat_factor": data_summary["hard_examples_repeat_factor"],
            "python_executable": sys.executable,
            "seed": args.seed,
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "num_workers": args.num_workers,
        },
    )
    
    print(f"✓ Model saved to models/url_cnn.pt")
    print(f"✓ Best validation F1: {(best_metrics or {}).get('f1', 0.0):.4f}")


if __name__ == "__main__":
    train()
